### ISSUE TITLE
Add Gizra Alpha information page + project

### ISSUE THREAD

**Issue by bricel** [Gizra/gizra.com#217]

**Comment by niryariv** [comment]
I suggest we wait until we decide on alpha's approach - incubator vs companies etc

**Comment by bricel** [comment]
We can start with the projects descriptions, no ?

**Comment by niryariv** [comment]
if it's an incubator it'll need it's own page, if not then we'll need to
give each project its own site

**Comment by bricel** [comment]
@niryariv - Yes it should have it's own page, let's write something when we can.

**Comment by RachelBaram** [comment]
@niryariv There is a push to do some enhancements to the website and this is a great opportunity to add Gizra Alpha. Let me know if we should be thinking on how and where to put it on the Gizra website or should this be shelved for now.

**Comment by niryariv** [comment]
Great. We basically need one page, ideally referenced in the nav header. For content we can start with [this](https://docs.google.com/document/d/1hpl-V6D6v6QMxw3ceTetfxevBJ3MdFYuwVAUtMKKDfc/edit), remove the last paragraph and add a contact form.

**Comment by RachelBaram** [comment]
@niryariv  If its just a link in the menu, there won't be anything explaining/leading people to go to the page. How about including it in the services page. There would be a sentence description and a link.

cc  @IshaDakota

**Comment by niryariv** [comment]
sounds good, services + header.

**Comment by RachelBaram** [comment]
@IshaDakota - Do we have time to open a page for Gizra alpha?
@niryariv - Is the below the text you wanted to include? Please review.

gizra | alpha

As a subsidiary of Gizra, Gizra Alpha’s goal is to apply the tools and methodologies Gizra has developed to creating new products. Realizing that there are sectors which are under-served by modern web technology, we’re working with domain experts from diverse fields such as municipal energy, auction houses, higher education and medical assistance to identify needs and create products that address them. 

Specifically, Gizra focuses on solutions that fit a web based software-as-service model, allowing users to switch from existing software products to a cloud hosted solution which can be continually improved without requiring dealing with installing and maintaining software, allowing businesses to outsource non-core activities and focus on their expertise.

At the heart of Gizra Alpha’s approach is a unique partnership model. We seek market sectors under-served by modern web technology and partner with domain experts who have identified a specific market need that can be addressed by Gizra’s development and product abilities. Our partners bring expertise and business contacts within their specific domain. 

An initial MVP (Minimum Viable Product) is defined in collaboration, and before implementation undergoes validation with several potential customers. If the response is positive, a development team builds an MVP version within three months. That version is provided to beta users, and based on their feedback molded into a complete product, ultimately launching a joint company.

Do you have a project you would like to discuss?

[Contact Form and information,Nir's contact information, Here]

[Gizra Alpha [Blog Post ](http://www.gizra.com/content/gizra-alpha/)Here]

**Comment by niryariv** [comment]
Not sure this is worth spending our time on right now (@amitaibu please correct me if I'm wrong)

**Comment by amitaibu** [comment]
Indeed, lets skip this one for now
