### ISSUE TITLE
add Partners section

### ISSUE THREAD

**Issue by niryariv** [Gizra/gizra.com#28]

**Comment by bricel** [comment]
@RachelBaram - Do you think we should keep this or close ?

**Comment by RachelBaram** [comment]
@bricel  This is listed as a topic to discuss for our marketing plan meeting. Let's make a decision then.

**Comment by RachelBaram** [comment]
@IshaDakota Any idea where we can include the information about our partnership on our website without opening a whole new page?

**Comment by IshaDakota** [comment]
If it's a simple text it could go in the "You may have seen our work" section.
