### ISSUE TITLE
Write up case study for Harvard Open Scholar as a blog.

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#288]
These blogs teasers will show up on the applicable Development services page. I will edit this so just get the main ideas down.

@amitaibu - Please assign the correct person to this if it is not you.

**Comment by amitaibu** [comment]
@RachelBaram can you please split those issues per case study - as each one is a separate task

**Comment by RachelBaram** [comment]
Content managed outside Github.
