### ISSUE TITLE
Fix Google score

### ISSUE THREAD

**Issue by bricel** [Gizra/gizra.com#317]
https://developers.google.com/speed/pagespeed/insights/?url=gizra.com&tab=desktop

**Comment by amitaibu** [comment]
Good thing that we keep the images as part of the repo - would much easier
to resize them

**Comment by bricel** [comment]
@YaronMiro - reducing the images should be enough.

**Comment by RachelBaram** [comment]
@DavidKohav  I am cleaning up the issue queue. Has this been resolved? Can I close this issue?

**Comment by DavidKohav** [comment]
@RachelBaram - This issue not resolved.

**Comment by RachelBaram** [comment]
@IshaDakota Can you help me understand if this is somthing that has been worked on?

**Comment by amitaibu** [comment]
f*ck google 😜
