### ISSUE TITLE
Narrow site text width.

### ISSUE THREAD

**Issue by YaronMiro** [Gizra/gizra.com#329]
http://baymard.com/blog/line-length-readability

**Comment by RachelBaram** [comment]
@IshaDakota  issue already opened. ;)

**Comment by IshaDakota** [comment]
@RachelBaram I should read more;) , so #345 is a sub-issue of this for blog posts only.

**Comment by amitaibu** [comment]
Blog posts are now narrow

**Comment by amitaibu** [comment]
David, Why assign to me?

**Comment by YaronMiro** [comment]
@guytepper 
You did a good work in narrowing the `blog post`.
Their are other sections across various pages of the site that are also too wide.
Please give the some love :)
