### ISSUE TITLE
Include "Contact us" webform to contact section

### ISSUE THREAD

**Issue by kazabooboo** [Gizra/gizra.com#384]
Add 5 fields web-form at the bottom on the site page. 
Name (required) 
Company / Organization  
Location: 
Email address  (required)  (email conventions verification) 
Body (required) 

Something like that: 
![image](https://cloud.githubusercontent.com/assets/16226208/14257790/5923c104-fa6d-11e5-9076-355c289e4029.png)

**Comment by kazabooboo** [comment]
@YaronMiro  I can't assign it to you. I have more examples if you like.

**Comment by IshaDakota** [comment]
come "competitors":
https://www.zivtech.com/contact
https://www.palantir.net/contact
https://fourkitchens.com/contact/

**Comment by IshaDakota** [comment]
@amitaibu or @bricel please advise where a general contact form should email. Setting to usoffice@gizra.com for the moment so I can test.

**Comment by amitaibu** [comment]
Done in #420
