### ISSUE TITLE
Optimize header & footer images

### ISSUE THREAD

**Issue by guytepper** [Gizra/gizra.com#387]
- [ ] Serve cropped images for lower screen resolutions
- [ ] Serve higher resolution images for high DPI devices
- [ ] Compress image files

**Comment by guytepper** [comment]
@amitaibu Do you have the original, full size images?

**Comment by amitaibu** [comment]
@YaronMiro ^^

**Comment by RachelBaram** [comment]
@guytepper Were you able to get the images required to work on this enhancement?

**Comment by guytepper** [comment]
@RachelBaram not yet.
