### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#407]
Something is wrong with the header on all pages but front
![fireshot capture 6 - 12 things i learned at my first drupal_ - http___www gizra com_content_12-thi](https://cloud.githubusercontent.com/assets/688507/15326673/7f3b850c-1c14-11e6-9a5a-b513e089adb8.png)

**Comment by amitaibu** [comment]
Seems to be a cache problem (see with http://www.gizra.com/?q2) it's working.

Should be auto fixed in a couple of minutes (cross fingers)
