### ISSUE TITLE
Align headers with the "new' left margin.

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#415]
After new margins are created for all (home,Meet the Team, Blog landing page, inside blogs) website pages #329, need to realign the menu,logo and text with the new left margin.

**Comment by IshaDakota** [comment]
@RachelBaram can you provide a screen shot that shows what you're talking about here?

**Comment by RachelBaram** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/14312543/15615487/6356a264-2447-11e6-9a64-807151c08ebf.png)

**Comment by IshaDakota** [comment]
@RachelBaram I think making the header narrow may look strange (particularly on wider desktop screens. I would prefer a layout strategy as shown in #346 which gives you the full container but shortens the line length for body text.

**Comment by RachelBaram** [comment]
I think we may be saying the same thing but using two languages. I don't think we should narrow the header but rather, align the Gizra logo and menu with the text (move it a little right). Or maybe we are not saying the same thing so we should have a quick chat. ;)

**Comment by IshaDakota** [comment]
phone discussion led to thinking about "balancing" the header to offset the visual disruption of the body container width.

see upcoming PR.
