### ISSUE TITLE
Update Team images

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#430]
Remove: Helena and Miro
Add: Adar, Anatoly, Savyon, Yoav, David B.

@bricel we'll need you photographic skills first

**Comment by RachelBaram** [comment]
This issue needs some attention. ;)

**Comment by amitaibu** [comment]
@RoySegall, we could use your camera skills :)

**Comment by amitaibu** [comment]
Or @DavidBronfen  - one of you has to do it 😉

**Comment by RoySegall** [comment]
I'll bring the camera tomorrow.

**Comment by DavidKohav** [comment]
We have the images, you just need to decide which to upload

**Comment by kazabooboo** [comment]
https://drive.google.com/open?id=0B30gFjtQyH8_WnlCdVAtaGJVa0k. Hi Res Pic. 
Hope it works

**Comment by RachelBaram** [comment]
@DavidBronfen As our talented photographer, you have also received the wonderful task of updating our team page pictures. The goal is to complete the minimum (new black and white pictures with the current hover option) by the end if this week. 
You can find all the information to complete this task at: https://docs.google.com/spreadsheets/d/1rjnazmSDEe_lviUGgygQdZU9sfLSyo6IeuyojJMhjy8/edit?ts=57cbc6e3#gid=0

**Comment by OritGeron** [comment]
@DavidBronfen we need to start
 -) Remove people who are gone
 -) Add the B&W pix of all employees

**Comment by DavidKohav** [comment]
@OritGeron - We do not have on the site people who are gone

**Comment by DavidKohav** [comment]
@DavidBronfen - need permission for drive
