### ISSUE TITLE
About h2 tags

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/gizra.com#435]
I'm sorry, but I didn't understand the idea behind this HTML code.
![about](https://cloud.githubusercontent.com/assets/5812423/15738387/b167217a-28b3-11e6-8dc9-445ae344bc2e.png)

**Comment by DavidKohav** [comment]
I think we can throw out the second h2 tag.

**Comment by DavidKohav** [comment]
![qqq](https://cloud.githubusercontent.com/assets/5812423/15738806/b23ad220-28b5-11e6-991a-d1c98a61e008.png)

**Comment by IshaDakota** [comment]
@DavidKohav Rachel and I are in the process of redoing this page along side the Services page #425 - we'll clean this up as well. Would love your eye on that PR as well.

**Comment by IshaDakota** [comment]
fixed per #439
