### ISSUE TITLE
Add a per tag page

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#440]
![tags](https://cloud.githubusercontent.com/assets/125707/15849127/a48e93fe-2c99-11e6-8da2-b68f889e4d76.jpg)

**Comment by amitaibu** [comment]
Url and screenshot please

**Comment by RachelBaram** [comment]
@amitaibu Tags go to [here](http://www.gizra.com/tags.html) instead of showing the [blogs](http://www.gizra.com/blog/) with the chosen tag.

**Comment by amitaibu** [comment]
*I've updated the title, as it's a feature not a bug (i.e. there was never a per-tag page).
* I've added a screenshot to the description as-well, since after it will be "fixed", we could go over the issue and see what the problem was
