### ISSUE TITLE
change text under "gizra alpha" in the services page

### ISSUE THREAD

**Issue by niryariv** [Gizra/gizra.com#442]
from:
"Gizra Alpha, a subsidiary company, applies our tools and methodologies to create new products. We partner with domain experts who have identified a specific market need that we can be address."

to: 
"Gizra Alpha, a subsidiary company, applies the tools and methodologies developed by Gizra to creating new products and companies, partnering with domain experts who identified a specific market need."

@RachelBaram @IshaDakota open to feedback on the text

**Comment by IshaDakota** [comment]
@niryariv I'm wondering if you want to link to the very good blog post you wrote from this text. Maybe the first two words "Gizra Alpha" or "developed by Gizra"

**Comment by niryariv** [comment]
@IshaDakota sounds good, i guess the link should be applied to "Gizra Alpha" at least until we set up its own page.

Regarding the text, a slight change:
"Gizra Alpha, a subsidiary company, applies the tools and methodologies developed by Gizra to creating new products and companies, in partnership with domain experts who identified a specific market need."

**Comment by IshaDakota** [comment]
deployed
