### ISSUE TITLE
Remove chevron pager for mobile

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#443]
It's superfluous.

**Comment by DavidKohav** [comment]
Can you please add more information about that? or add image?

**Comment by IshaDakota** [comment]
On mobile, because the content is so close together, the scroll icons are
unecessary. We should remove them from view on smallest screens.

**Comment by DavidKohav** [comment]
I do it know.

**Comment by DavidKohav** [comment]
Done in #396

**Comment by IshaDakota** [comment]
merged & deployed
