### ISSUE TITLE
Make links to "About" scroll to anchor

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#446]
Links to the "About" menu item should load at the top of the page then scroll to the "about" anchor, in a similar fashion to the way authors link from blog posts (which is a little bit broken).

**Comment by IshaDakota** [comment]
#447

**Comment by IshaDakota** [comment]
@amitaibu can you assign to someone with more JS-fu than I to do this and fix #447.

**Comment by amitaibu** [comment]
@ItamarGronich this one is yours, if you have questions on what is exactly needed @IshaDakota is your address.

**Comment by IshaDakota** [comment]
no longer relevant.
