### ISSUE TITLE
Make post links a bit more prominent

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#450]
@IshaDakota I think it's easy to miss the post's links

![faithful_elm_and_the_amazing_router_](https://cloud.githubusercontent.com/assets/125707/16112755/87171c7c-33c1-11e6-8c6a-e4e6e2c59f8a.jpg)

 maybe make them a little darker, or an underline?

![faithful_elm_and_the_amazing_router_](https://cloud.githubusercontent.com/assets/125707/16112780/ad4eeac8-33c1-11e6-8287-3bd8fdd2caee.jpg)

**Comment by IshaDakota** [comment]
yeah, I was trying to "soften" the links a little, but they look too "soft."
