### ISSUE TITLE
Improve readability in services page

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#453]
http://www.gizra.com/services/#

![services](https://cloud.githubusercontent.com/assets/125707/16131414/be2634b4-3416-11e6-8878-2a568b2be8e0.jpg)

1. I think that due to the image background it's a bit hard to read the text
1. The link is not referencing anywhere

**Comment by IshaDakota** [comment]
fixed in #452 in that the link was removed. It was put there to demonstrate links on that page, but somehow made it through (probably because it was so hard to see). If we do put a link there, we should do it in white.
