### ISSUE TITLE
Create layout based on flexbox instead of bootstrap

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#454]
From #445 

> I'd love getting read of bootstrap and move from the old school float oriented grids to flexbox. So it will become properly responsive on all devices, as anyway we don't care about IE9 and downwards

I'll investigate a little and put notes/finding here. I'm intrigued with 2 possible reservations:
1. Bootstrap gives us more than the grid - although probably not that much.
2. I've seen some arguments that flexbox doesn't handle full page grid-like layout as well as it serves to handle smaller parent/child div arrangements.

**Comment by IshaDakota** [comment]
> we don't care about IE9 and downwards

Nor[ does our audience](https://docs.google.com/a/gizra.com/spreadsheets/d/1BzOOoqGBzMsRVlUYf18zsESaLfSdBGLBtrXYCVBqyd4/edit?usp=sharing).

**Comment by amitaibu** [comment]
> I've seen some arguments that flexbox doesn't handle full page grid-like layout

I have not seen or experienced this case. 

btw, I forgot to mention we are now days practicing [Bem](https://css-tricks.com/bem-101/) 😉

**Comment by amitaibu** [comment]
> Bootstrap gives us more than the grid - although probably not that much.

I think it doesn't give that much. With flexbox and [normalize.css](https://necolas.github.io/normalize.css/) we can start from a clean slate.

btw, I've been also looking at [semantic-ui](http://semantic-ui.com/) but I have a feeling it requires us to be very disciplined, but no automatic mechanism to enforce it.

**Comment by IshaDakota** [comment]
> btw, I forgot to mention we are now days practicing Bem

Can you point to a project - I'd like to have a look/see.

> btw, I've been also looking at semantic-ui 

To me it seems smart, but a little too smart for itself maybe.

Have you looked at Bootstrap 4?

**Comment by amitaibu** [comment]
> Have you looked at Bootstrap 4?

I have - but I'm not sure if we need it.

**Comment by IshaDakota** [comment]
no longer relevant.
