### ISSUE TITLE
CDL's URL is the real URL

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#462]
In `/projects`,  it is listed as `Project Demo` - however it's actually the _real_ site http://gizra.github.io/CDL/

And btw, here's the Spanish version of it http://gizra.github.io/CDL-ES/

![project_portfolio](https://cloud.githubusercontent.com/assets/125707/16544690/03556dee-4118-11e6-882f-5db3b2f11ae5.jpg)

**Comment by IshaDakota** [comment]
Is the exhibit still active?

**Comment by niryariv** [comment]
Not in the museum itself

**Comment by RachelBaram** [comment]
@IshaDakota Can this be closed?

**Comment by IshaDakota** [comment]
yeah... I still think this is the best description for the link.
