### ISSUE TITLE
8 reasons to chose Drupal

### ISSUE THREAD

**Issue by RoySegall** [Gizra/gizra.com#463]
When I visited HP HQ for a meetup someone asked me "Why keep using Drupal?"
couple of highlights:
1. Content oriented - mean.js and other solutions can't provide the same exprience to create data structure and manage content.
2. Plugins, hooks, events, services - All above have awesome tools for developers which I don't think exists in such large scale on other frameworks
3. Commerce expreince - Tools as Commerce kickstart and all the libraries they create for symfony are awesome!
4. OG - You can't find it in any other framework. And I'm willing to put my macbook pro on this one
5. I18n
6. awesome community
7. Uncompromising QA for modules
8. Migration already come with Drupal 8 - easy to migrate OLD drupal sites.

**Comment by RachelBaram** [comment]
@RoySegall What is the reason you closed this?
