### ISSUE TITLE
Accessibility in CI

### ISSUE THREAD

**Issue by nirgn975** [Gizra/gizra.com#468]
Run accessibility audits with [a11y](https://github.com/addyosmani/a11y) in Travis-Ci. This tool is based on [Google Chrome accessibility developer tools](https://github.com/GoogleChrome/accessibility-developer-tools), it's just integrate PhantomJS already.

Don't know if we want it (@amitaibu ?). If we are, maybe @DavidKohav want to take it?

**Comment by DavidKohav** [comment]
I think @yoavi  did it.
@yoavi - Which project did  you add it?

**Comment by ybaras** [comment]
It was in in Gizra/Danel#339 but the attempt was never completed, I was called away to other issues.

**Comment by nirgn975** [comment]
Ok, so if it's not relevant I assume this is too not relevant - closing.

**Comment by DavidKohav** [comment]
@amitaibu / @bricel - 
Do you want me to try to do so in the contribution?

**Comment by amitaibu** [comment]
Please write the steps you want to take.

**Comment by RachelBaram** [comment]
@IshaDakota Need your help to understand if this is still relevant.

**Comment by IshaDakota** [comment]
@DavidKohav if this is something you have a particular passion for or want to figure out for the sake of other projects (and have time for), go ahead. Otherwise, just close.
