### ISSUE TITLE
Meta tags validation

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#469]
Implement a Behat test to validate SEO meta tags on all pages. Title H1, Description between 150-160 characters, and Keywords.

September 2016

**Comment by IshaDakota** [comment]
@RachelBaram  [Google doesn't use keywords in page ranking](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html). Contextual tags (with links to other like posts) are better.

**Comment by RachelBaram** [comment]
It's not either or.  This has a role beyond SEO. From what I have been
reading this is a best practice and making this an automatic test should
minimize our efforts. Please clarify what you are suggesting specifically
for this. I may be missing something here so do explain. :)

https://www.searchenginejournal.com/important-tags-2016-seo/156440/#readfull

https://blog.kissmetrics.com/meta-description-magic/

On Sep 9, 2016 15:33, "Adam Stewart" <notifications@github.com> wrote:

@RachelBaram <https://github.com/RachelBaram> Google doesn't use keywords
in page ranking
<https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html>.
Contextual tags (with links to other like posts) are better.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Gizra/gizra.com/issues/469#issuecomment-245900071>, or mute
the thread

**Comment by IshaDakota** [comment]
>It's not either or. 
I'm talking only about Metatag Keywords.

Metatags (some, are important - there are many [types](http://www.metatags.org/all_metatags))

Metatag Keywords are irrelevant, or worse, can have negative impact.

Tags on posts (not metatags, but visible to the screen and which link to other content that is useful) is good.

**Comment by IshaDakota** [comment]
@RachelBaram Creating a pull request to demonstrate what I'm talking about... and a little more.

**Comment by RachelBaram** [comment]
Let's talk first. Concerned that time and effort is going to the wrong
place because we are not on the same page. A quick chat should remedy that.
:)

**Comment by IshaDakota** [comment]
Too late ;) minimal time/effort and it shows more than my words could.
