### ISSUE TITLE
Blog post: Elm & Electron.

### ISSUE THREAD

**Issue by nirgn975** [Gizra/gizra.com#471]

**Comment by RachelBaram** [comment]
@nirgn975 The alternative title "Elmctron - Build Desktop Apps with Elm and Electron" includes some important keywords that the current title is missing. Do you feel comfortable changing it?

**Comment by nirgn975** [comment]
@RachelBaram Yep.

**Comment by RachelBaram** [comment]
@nirgn975 Great. Can you please change it? ;)

**Comment by RachelBaram** [comment]
@nirgn975 Can you please change the title to: Elmctron - Build Desktop Apps with Elm and Electron?  Thanks!

**Comment by nirgn975** [comment]
@RachelBaram Deployed ([link](http://www.gizra.com/content/elm-electron-build/)).
