### ISSUE TITLE
Recommended offer for the Blog section in the homepage

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/gizra.com#486]
I feel on the widescreens that we have extra white space.
I want  to recommend to add more two blogs to cover this extra white space and
more exposure to other topics.

![selection_013](https://cloud.githubusercontent.com/assets/5812423/18229935/ef739db6-7293-11e6-86ed-bf18f76eb93e.png)

**Comment by DavidKohav** [comment]
@IshaDakota - FYI

**Comment by RachelBaram** [comment]
This is talked about in issue #470.  @IshaDakota It really looks bad on a PC. Your input to address this will be really helpful. Thanks!

**Comment by DavidKohav** [comment]
Ok, I close this issue .
