### ISSUE TITLE
Remove TBD's pix

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/gizra.com#501]
You don't need the dog and the cat if you have 100% of the rows.
And I don't see the hover with the github and email info
![selection_005](https://cloud.githubusercontent.com/assets/5812423/18576809/91fab954-7bed-11e6-8f14-aa51d589a02d.png)

**Comment by OritGeron** [comment]
@DavidBronfen you can add the wolf pix and another pix of your choosing. 
https://drive.google.com/drive/folders/0BxTGz2bxLkpFOHoxVFJ2TlAzbXc

**Comment by OritGeron** [comment]
@DavidBronfen Just remove the 2 pix until we will next time. Thanks!
