### ISSUE TITLE
Savyon's avatar has vanished

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#509]
![fireshot capture 134 - gizra s blog - http___www gizra com_blog_](https://cloud.githubusercontent.com/assets/688507/18650006/6a7eb7ca-7e88-11e6-838c-4ab1b146e8e8.png)

maybe we we deployed with an outdated master? I'm merging #494 so that should probably fix it.

**Comment by IshaDakota** [comment]
yup, redeploying unvanished @savyoncohen !

leaving open for @amitaibu in case I inadvertently rolled back something.
 
![fireshot capture 135 - design web development i gizra - http___www gizra com_](https://cloud.githubusercontent.com/assets/688507/18650203/4b28b460-7e89-11e6-8afe-bed0844be492.png)

**Comment by amitaibu** [comment]
So far so good :)
