### ISSUE TITLE
Bring Gizra 'Projects' up to the home page

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#516]
Our best selling points are buried too many clicks away. Would like our projects list to be the second thing to see after the above the fold text.

**Comment by RachelBaram** [comment]
Nice example of how projects are displayed: http://www.prime-do.com/

**Comment by IshaDakota** [comment]
@RachelBaram I'm not clear on the project here... are we 

- moving the projects section from the "our work" page; or
- designing something like the example above

Those are 2 different tasks - I have comments on both, but let's clarify first.

**Comment by RachelBaram** [comment]
@IshaDakota  At minimum, we should move the project slider.  Ideally, would be to design something like the example above (since none of us like a slider and our major selling points are our projects.) So based on your estimate of time for each, I see that there are three options:
1. move slider and then design a new way to present our projects (this is probably best if moving the slider is little (1/5) work and the new design is a lot (4/5) of work).
2. design something new (this is probably best if it is to little (1/5) to medium (3/5) amount of work)
3. only move the slider (this is probably best if the new design is a massive amount of work (5/5)
What do you suggest?

Your opinion?

**Comment by IshaDakota** [comment]
in #522
