### ISSUE TITLE
Smartphone increase in 404 pages

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#517]
I received this email:
![404](https://cloud.githubusercontent.com/assets/14312543/18886863/6b33c6d8-84fa-11e6-809f-00b0d39c1017.png)

**Comment by IshaDakota** [comment]
@RachelBaram can you send me the report from the "Check Smartphone Errors" link.

**Comment by IshaDakota** [comment]
@RachelBaram I think this might have been temporary, but I need Search Console access to check it out.

**Comment by RachelBaram** [comment]
@bricel Can you determine if we need to do anything with this?

**Comment by bricel** [comment]
@DavidKohav - Can you please check the links that return 404.

**Comment by DavidKohav** [comment]
@bricel - Please add me to the analytics.

**Comment by RachelBaram** [comment]
More information about the errors:
![drupal8-behat error](https://cloud.githubusercontent.com/assets/14312543/19218946/27192dee-8e0f-11e6-9dcd-2647cccba1f0.png)
![drupal8-behat](https://cloud.githubusercontent.com/assets/14312543/19218947/271cefce-8e0f-11e6-9c6a-1a085eb7d0ef.png)

**Comment by DavidKohav** [comment]
Hi @RachelBaram - After checking, I see that the Giza feed is not updated,
and because of that the aggregators showing links that not relevants.

I will fix the feed and will let you know after fixing.

**Comment by DavidKohav** [comment]
@bricel - I see in the wiki :
![selection_060](https://cloud.githubusercontent.com/assets/5812423/19678775/d8f8c700-9aa7-11e6-925a-c046ddc2401d.png)

We do not have the ```feed:``` before the URL
Please let me know if this the right direction for the solution.

**Comment by DavidKohav** [comment]
@bricel - In the FEED module (from drupal) 
I see that it has property ```isPermaLink="false"```, and we don't have.

**Comment by bricel** [comment]
![search_console_-_crawl_errors_-_http___www_gizra_com_](https://cloud.githubusercontent.com/assets/165644/21885452/70a38d6e-d8c0-11e6-92a6-1e35dd057d1e.png)
