### ISSUE TITLE
Blog post: jekyll-starter-kit Yeoman Generator

### ISSUE THREAD

**Issue by nirgn975** [Gizra/gizra.com#519]
[link](https://github.com/nirgn975/jekyll-starter-kit)

**Comment by IshaDakota** [comment]
@nirgn975 if you don't write a description, you don't get a fancy twitter card on twitter or image facebook. Also we don't get good SEO juice without a meta-description. Particularly inportant for a topic as hot as web apps.

Can you write one?

**Comment by IshaDakota** [comment]
@nirgn975 also, the first link to Jekyll is relative to the site.

**Comment by amitaibu** [comment]
I have pushed a fix for the jekyll link, but have problem deploying. @IshaDakota can you `grunt deploy` from `master` please

**Comment by amitaibu** [comment]
> I have pushed a fix for the jekyll link, but have problem deploying

Deployed.

**Comment by IshaDakota** [comment]
I added a description as well. @nirgn975 feel free to change if you don't like.
