### ISSUE TITLE
Similar blog tags

### ISSUE THREAD

**Issue by liatsade** [Gizra/gizra.com#524]
@RachelBaram I know you do some reordering in tags, so please note that there is "Migration" and also "Migrate". Actually they are the same, I think we should merge them.

![tags](https://cloud.githubusercontent.com/assets/20393485/19221233/09c3ee4e-8e48-11e6-97a1-aeb9bd60b0c8.jpg)

![tags](https://cloud.githubusercontent.com/assets/20393485/19221251/6375e730-8e48-11e6-890b-bcf447931e76.jpg)

**Comment by amitaibu** [comment]
Liat, thanks - go ahead and create a pr to fix it.

**Comment by RachelBaram** [comment]
I have a list of about 35 blogs that I plan  on changing/merging/adding
tags. This is one of them. Great catch.

**Comment by liatsade** [comment]
@RachelBaram working on it #525
