### ISSUE TITLE
Employee names & titles on team page are misaligned on mobile view.

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#528]
For employees with long titles, their name and title is misaligned on mobile view.
 
![image](https://cloud.githubusercontent.com/assets/14312543/19869206/052bb998-9fb4-11e6-9737-a11549856737.png)

**Comment by amitaibu** [comment]
@DavidBronfen if you can look at it please (not urgent)

**Comment by DavidBronfen** [comment]
@RachelBaram Which screens or devices did you use to test the site??
