### ISSUE TITLE
Google Analytics Warning

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#543]
**From analytics:**
Property http://www.gizra.com is receiving data from redundant hostnames. Some of the redundant hostnames are:
gizra.com
www.gizra.com
Redundant hostnames are counted as separate rows in reports, so hits that are going to the same page on your site from different hostnames will be split into multiple rows. With data split across multiple rows, traffic to specific pages will appear lower than it actually is.

To avoid this problem, consider setting up a 301 redirect from one of your redundant hostnames to the other, or create a search-and-replace filter that strips "www." from hostnames.

Google Tag Assistant Recordings can help you verify that your redirect is setup correctly, or that your filter is working as intended.

**Solution:** https://www.ohow.co/fix-redundant-hostnames-notification-in-google-analytics/

@bricel I don't have access permissions to fix.

**Comment by bricel** [comment]
@IshaDakota there is already a 301 on the domain, it's there for a while, when did you see that we got access to the domain without www ?
![image](https://cloud.githubusercontent.com/assets/165644/21470314/020acf6c-ca8c-11e6-8c90-90a9de5759f8.png)

**Comment by IshaDakota** [comment]
check analytics - the warning is from November 2016. The doc I read said to both create the redirect and use the analytics feature.

... or we could just probably safely ignore.

**Comment by bricel** [comment]
OK, resubmitted the test, we'll have results within 24H.

**Comment by IshaDakota** [comment]
resolved:
![image](https://cloud.githubusercontent.com/assets/688507/21720704/3d19fbfc-d3ea-11e6-85d9-cb337753235f.png)
