### ISSUE TITLE
Add completed project descriptions to the site

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#544]
This is needed for #522 - We have a screenshot, need a paragraph description.

**Comment by RachelBaram** [comment]
@IshaDakota Is there some sort of requirement for the website that the current [project description](https://docs.google.com/document/d/1ZhL0hcMG05x5lwh-YI4pLQHZKjLVvyy33sFw2qv_pUQ/edit#) not satisfy?

Client: United Nations Population Fund
URL: unfpa.org
Date: 2015 - 2018 (ongoing)
 
Project Description: 
Build and maintain 160 websites, including the main organization’s website.
Out of the total four companies chosen to take on this task, Gizra was specifically selected for expertise in Drupal, continuous integration, and high-level quality assurance.  Gizra helped plan the architecture and performs the code review for all the sites as well as setting up a new Hosting environment that reduced the cost and boosted performance considerably. Complex Drupal tasks are handed over specifically to our developers.

**Comment by IshaDakota** [comment]
@RachelBaram No, i had just not seen this on the project list - can we instead use this issue to list descriptions that need to be added to the website?
