### ISSUE TITLE
Team page pix

### ISSUE THREAD

**Issue by OritGeron** [Gizra/gizra.com#555]
|   AMITAI| BRICE  | ORIT  | RACHEL  |
|---|---|---|---|
|   ROY| NADER  | OR  | ADAM  |
|   ITAMAR| EFRAT  | LIAT  | NOAM  |
|   PAVEL| ANATOLY  |  YOAV | SAVYON  |
|   DAVID| ITAMARG  |  DAVIDH | RYAN  |
|   ALVARO| LUIS  |  ARON | YOU?  |

Ryan pix
https://drive.google.com/a/gizra.com/file/d/0BxTGz2bxLkpFTUU2NkNYXzNsVHVHTWVSMVA2blo5QUc2NDhv/view?usp=sharing

Luis Logo
https://drive.google.com/a/gizra.com/file/d/0BxTGz2bxLkpFQnd2YWhXS285XzNsblY3bnRhVzdYQkprZ0JF/view?usp=sharing

https://drive.google.com/a/gizra.com/file/d/0BxTGz2bxLkpFSExSaVBXcWktTWJoYzNJaEtJaDZNVmozbDRj/view?usp=sharing

**Comment by amitaibu** [comment]
Sorry, but we're not placing a logo on the team's page..

**Comment by OritGeron** [comment]
@amitaibu Sure. Sent Luis a new request

**Comment by OritGeron** [comment]
![img_0469](https://cloud.githubusercontent.com/assets/7068965/22417486/31090a82-e6dd-11e6-9338-c90bba724b39.JPG)
@DavidBronfen this is Alvaro's pix, Please add it to our Team page.

**Comment by amitaibu** [comment]
@DavidBronfen can you take care of this please, so we can update the Team page.

**Comment by amitaibu** [comment]
cc @RachelBaram

**Comment by DavidBronfen** [comment]
@OritGeron What about Luis?

**Comment by DavidBronfen** [comment]
@OritGeron And also Alvaro photo is still with a white background, should I wait for a photo with a black background or just place the one that attached here?

**Comment by amitaibu** [comment]
Should be with a black background (/cc @alvar0hurtad0 )

**Comment by amitaibu** [comment]
> What about Luis?

@rosenstrauch ^^ :)

**Comment by alvar0hurtad0** [comment]
This was last picture I sent, I've received this morning a black chroma to take the picture.

![bnalvaro](https://cloud.githubusercontent.com/assets/1130114/22971758/12a2c08c-f377-11e6-9a4a-733703bed515.png)

**Comment by DavidBronfen** [comment]
@amitaibu Should I wait to @rosenstrauch photo or I'll add it later?

**Comment by amitaibu** [comment]
no need to wait

**Comment by amitaibu** [comment]
@DavidBronfen can we use Alvaro's above image? ^^

@rohanorton we'll need you here as-well :) @DavidBronfen can give instructions

**Comment by DavidBronfen** [comment]
@amitaibu It's a `png` file, can we use it instead of jpg?

**Comment by amitaibu** [comment]
lets convert to jpg, until we get a better quality one.

**Comment by RachelBaram** [comment]
@amitaibu Any 'easy' way to change the design so the size/format of the pictures on the page is more simple - headshots with white background. It will be easier to add new employees to the page. It is a shame this page is not up to date.

**Comment by amitaibu** [comment]
I don't think we need to change the design. Looking at the current team page, we have 4 remote people that were able to do it.

**Comment by RachelBaram** [comment]
Ok guys! Let's get you on the team page.  @alvar0hurtad0, @rosenstrauch, @noamoss, @rohanorton. Please send a picture (see the [team page](http://www.gizra.com/team/)) with a black background. If you have any questions on format please contact @DavidBronfen.

**Comment by alvar0hurtad0** [comment]
@DavidBronfen I've a new picture:

![5](https://cloud.githubusercontent.com/assets/1130114/26298006/d38c049e-3ed5-11e7-864f-a1a28d061ba8.jpg)

feedback?

**Comment by DavidBronfen** [comment]
@alvar0hurtad0 This picture is better than the others you've posted, don't you think? :)

**Comment by alvar0hurtad0** [comment]
I only know about drupal ... :P

**Comment by IshaDakota** [comment]
closed as stale
