### ISSUE TITLE
UX improvement for tags

### ISSUE THREAD

**Issue by RoySegall** [Gizra/gizra.com#562]
It might be related to the tag widget component, but it would be if a user could clear all the tags choice when viewing the team:
![the_team](https://cloud.githubusercontent.com/assets/1222368/22920510/0f0df880-f29e-11e6-917b-01cd163d0502.png)

When I filtered for Rachel I needed to remove all the tags to see the pictures:
![the_team](https://cloud.githubusercontent.com/assets/1222368/22920583/6aa9ce26-f29e-11e6-8fec-c4065d87d8d8.png)

**Comment by amitaibu** [comment]
We made sure to push the pretty ones to the bottom - so basically it's just Brice and me that are covered 😉
