### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by nqthqn** [Gizra/gizra.com#570]
> If you **doesn't** take into account all the discussions over the past two years, then you could say that we have been discussing the “new” topic quite intensively for almost three months now.

> If you **don't** take into account all the discussions over the past two years, then you could say that we have been discussing the “new” topic quite intensively for almost three months now.

http://www.gizra.com/story/what-matters/

This may _presently_ be a problem. Perhaps I is mistaken.

Love the site, btw. <3

**Comment by nqthqn** [comment]
> Once you are the car, you start unbuttoning your suit.

also needs some string interpolation

> Once you are **in** the car, you start unbuttoning your suit.

**Comment by amitaibu** [comment]
Thanks @nqthqn! We'll fix them soon :)
