### ISSUE TITLE
Ryan's github link to DavidHernandez account

### ISSUE THREAD

**Issue by alvar0hurtad0** [Gizra/gizra.com#578]
On:
http://www.gizra.com/team/
![download](https://cloud.githubusercontent.com/assets/1130114/23498144/85b26284-ff26-11e6-881e-3dc20e2875b2.png)

**Comment by amitaibu** [comment]
Oops. Maybe they are the same person? ;)

Care to create a PR?

**Comment by alvar0hurtad0** [comment]
I'll do.
