### ISSUE TITLE
Add links  [blog post] #584

### ISSUE THREAD

**Issue by OritGeron** [Gizra/gizra.com#585]
https://github.com/Gizra/gizra.com/pull/584#issuecomment-284996705

Add link:

- [x] Job posting in "apply" 
![it_s_not_a_wonder__women_](https://cloud.githubusercontent.com/assets/7068965/23699028/6359b230-03f6-11e7-875f-68e95867107d.jpg)

- [x]  Amitai's blog post  https://www.facebook.com/amitai.burstein/posts/974158179333075
![it_s_not_a_wonder__women_](https://cloud.githubusercontent.com/assets/7068965/23700367/3bab160c-03fb-11e7-84f6-f0c9a46c14b7.jpg)

**Comment by RachelBaram** [comment]
#586 done by Amitai for viral FB post

**Comment by nader77** [comment]
Ok, I'll do the other link on @amitaibu's PR.

**Comment by nader77** [comment]
Deployed:
http://www.gizra.com/content/its-not-a-wonder-women/

You can close this issue if all is good.
