### ISSUE TITLE
Fix  spelling at the images of "Why Drupal?" blogpost

### ISSUE THREAD

**Issue by AronNovak** [Gizra/gizra.com#594]
In the text, we have "privilege", in the images, there's  "priviledge".
It seems it is not a valid form: http://www.ldoceonline.com/spellcheck/english/?q=priviledge (but native speakers might disagree).
In some places, I see that they state that priviledge is an obsolete form, but likely most people will just find it strange.

Example: http://www.gizra.com/assets/images/posts/why-drupal/end-of-priviledge.png

**Comment by IshaDakota** [comment]
Thanks @AronNovak - @DavidHernandez is already working on updating the image - unfortunately I merged it before we noticed.
