### ISSUE TITLE
Broken image on deploy

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#596]
![gizra_s_blog](https://cloud.githubusercontent.com/assets/125707/26253476/372912e2-3cbc-11e7-957a-7fcd78c11e43.jpg)

(Might be a case sensitive name of the file)

**Comment by IshaDakota** [comment]
hmm . Oddly, on local it's fine. It must be gremlins. I'll try to redeploy and see if that works.

**Comment by IshaDakota** [comment]
rebuilt the site directory and it's fine. @amitaibu Is there a gulp command for that? I just deleted the directory contents and `gulp publish`
