### ISSUE TITLE
Use `include thumbnail.html` for images

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#603]
Hi @DavidHernandez @RoySegall - thank you for your recent posts!

It would be great if you could create PRs to switch to using the [include](https://github.com/Gizra/gizra.com/blame/256e690358c6d7b35363d2eaa5ab1a82ff61fd0a/src/_posts/2016-09-22-yesod-drupal.md#L159) format for the images, as it makes sure it's properly resized and bordered. Otherwise, it looks a bit broken:

![write_your_first_bot_using_nuntius](https://cloud.githubusercontent.com/assets/125707/26755518/739d8848-4897-11e7-8498-e60e50dfa48e.jpg)

// cc @IshaDakota

**Comment by RoySegall** [comment]
I'll update my blog post tomorrow morning(David's blog post has a specific structure so I'll let him change that) and update the readme file on the way.
