### ISSUE TITLE
Create a map indicating locations of Gizra's team.

### ISSUE THREAD

**Issue by nedSaf** [Gizra/gizra.com#606]

**Comment by IshaDakota** [comment]
merged, but the deploy won't work for me. I can see it fine locally, but somehow the new JS isn't compiled for the live site. @amitaibu any tip?

**Comment by nedSaf** [comment]
@IshaDakota I see it fine on the live site:
https://www.gizra.com/team/
![gizra-team](https://user-images.githubusercontent.com/7369740/32141191-63f2ea3c-bc82-11e7-8471-d49a61162ed1.jpg)


Maybe it was cache.

**Comment by amitaibu** [comment]
Thanks. Needs some small css fix

![the_team_and_trackingtime___time_tracker](https://user-images.githubusercontent.com/125707/32141199-ad8c6448-bc82-11e7-8ee2-2878f471d43c.jpg)

**Comment by nedSaf** [comment]
👍

**Comment by IshaDakota** [comment]
small fix deployed
