### ISSUE TITLE
update team members page

### ISSUE THREAD

**Issue by OritGeron** [Gizra/gizra.com#608]
![the_team](https://user-images.githubusercontent.com/7068965/30260658-63581e48-96d1-11e7-9a19-c701eb95aabf.jpg)

**Comment by nedSaf** [comment]
@OritGeron All are done in #607 also added Noam, Alex, Luis, Ronan, and Alan.

If this sounds good, you can close this issue.

**Comment by amitaibu** [comment]
Alan is out to his studies - so you can remove

> Noam, Alex, Luis, Ronan, and Alan.

Great, do we have images for all the above people? If not, please don't add

**Comment by nedSaf** [comment]
Ok removing.
