### ISSUE TITLE
Update Team page [1h]

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#610]
Need to make the following changes to the Team page:
1. Orit - change title to Operations Director
2. Efrat - move up to after Orit and change title to "Israel/Europe Executive Director"
2.  Rachel - change to "Business Development and Strategy"
3.  Liat - change to "UI/UX Specialist and Client Training"
4. Take out Itamar
5. Add Alex (@OritGeron - can you share his picture here)

**Comment by RachelBaram** [comment]
@IshaDakota Do the above titles sound OK for US clients?

**Comment by RachelBaram** [comment]
@efratn Who can I put on this?

**Comment by nedSaf** [comment]
👍  @OritGeron Please share the pic so I can do it this WE.

**Comment by nedSaf** [comment]
Got the photo via email :)

**Comment by IshaDakota** [comment]
merged & deployed
