### ISSUE TITLE
Pager for blog includes podcasts

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra.com#648]
![prototyping_with_css_grid](https://user-images.githubusercontent.com/688507/35640678-7445e4ca-0683-11e8-989c-f4aa4859ff9b.png)

While I was really proud of [how I did the pager for podcasts](https://github.com/Gizra/gizra.com/blob/master/src/_layouts/podcast.html#L53) - I neglected to think about the impact on the pager for blogs.  We can't use the same method because there's no incremental post number... and we can't use `page.next` because it will include podcasts, since they are posts.

## Options

- Some Liquid template magic.
- Make podcasts it's own collection - the trick there is the Drupal planet RSS feed - we'd need to concatenate those arrays and sort by date (I think). Or ask Drupal Planet to accept another feed.

Anyone with templating skills want to try this one @amitaibu @nedSaf @mariano-dagostino - I've reached my podcast time box for the week ;)

**Comment by RachelBaram** [comment]
@nedSaf Friendly reminder.  I know you are super busy.

**Comment by nedSaf** [comment]
👍 Thanks for the reminder.

**Comment by IshaDakota** [comment]
@nedSaf passing this to @DavidHernandez to take a stab at if he has time on Friday.

**Comment by DavidHernandez** [comment]
@IshaDakota I've reviewed the PR and I think is good to be merged.

**Comment by IshaDakota** [comment]
deployed
