### ISSUE TITLE
SEO: Add h2 to blog page [.5h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#663]
Blos posts title is great SEO resource as they keep updating (showing the site is not frozen), with words that describe what we really do (i.e. elm, Travis, Drupal, Tests etc..) and leads to a relevant content (i.e. the blog post).

Therefore, in https://www.gizra.com/blog/ we should add the posts as h2, to emphasize their relevance to the user. Currently, they appear only as `alt` for the images (which is good, but not enough).

![image](https://user-images.githubusercontent.com/3581741/36640650-dac20902-1a2b-11e8-9d80-0d987ec1562c.png)

**Comment by IshaDakota** [comment]
merged & deployed
