### ISSUE TITLE
SEO/Accessibility: Homepage links don't have a discernable name [0.5h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#671]
Link text (and alternate text for images, when used as links) must be discernible by a screen reader, must not have a duplicate label, and must be focusable.

([read more](https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse))

![image](https://user-images.githubusercontent.com/3581741/37269112-b20e4604-25d1-11e8-99f5-969fa7edd176.png)

**Comment by IshaDakota** [comment]
deployed
