### ISSUE TITLE
SEO/Accessibility: Homepage and Team page: improve background/foreground contrast [1h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#672]
All text elements must have sufficient contrast between text in the foreground and background colors behind it in accordance with WCAG 2 AA contrast ratio thresholds. [read more](https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse)

Homepage:
![image](https://user-images.githubusercontent.com/3581741/37269170-f6e5e53e-25d1-11e8-8877-7b60bba2100e.png)

Team page:
![image](https://user-images.githubusercontent.com/3581741/37271291-e60b6d2a-25da-11e8-9ddc-c13b00ea6d8f.png)

**Comment by IshaDakota** [comment]
This doesn't seem to be a big issue and I'd prefer not mess with the style at the moment. @noamoss , ok if we close?

**Comment by noamoss** [comment]
sure.
