### ISSUE TITLE
SEO/Performance: Open _blank links with "noopener" tag [0.5h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#675]
should be applied site-wide, in all `_blank` links in the site, currently, two are known on homepage:

https://developers.google.com/web/tools/lighthouse/audits/noopener: 
> When your page links to another page using target="_blank", the new page runs on the same process as your page. If the new page is executing expensive JavaScript, your page's performance may also suffer. See The Performance Benefits of rel=noopener for more information.
> 
> On top of this, target="_blank" is also a security vulnerability. The new page has access to your window object via window.opener, and it can navigate your page to a different URL using window.opener.location = newURL. See About rel=noopener for a demo and explanation of the vulnerability.
> 
> Recommendations
> Add rel="noopener" to each of the links that Lighthouse has identified in your report. In general, always add rel="noopener" when you open an external link in a new window or tab.
> 
> <a href="https://examplepetstore.com" target="_blank" rel="noopener">...</a>

for example, on the homepage:

![image](https://user-images.githubusercontent.com/3581741/37269399-cc206cba-25d2-11e8-9f30-8654498d6494.png)

on the team page:
![image](https://user-images.githubusercontent.com/3581741/37271023-d745dcae-25d9-11e8-907e-ea888b160c13.png)

**Comment by IshaDakota** [comment]
deployed
