### ISSUE TITLE
SEO/Performance: Homepage Investigate how to improve loading time [1h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#676]
Notice, this issue is for investigation and opening follow up issues for the selected items.

Based on [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=gizra.com) and Lighthouse check:

![image](https://user-images.githubusercontent.com/3581741/37269538-7addac36-25d3-11e8-997f-66833266096f.png)

![image](https://user-images.githubusercontent.com/3581741/37269518-64611632-25d3-11e8-8757-dee86cee06b9.png)

## Consider the following tasks (with a follow-up issue for each you approve):

* [ ] ways to reduce render-blocking stylesheets ([read more](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources))

![image](https://user-images.githubusercontent.com/3581741/37269567-9a55ebbe-25d3-11e8-9783-836361b59866.png)

----

* [ ] ways to reduce render-blocking scripts ([read more](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources))

![image](https://user-images.githubusercontent.com/3581741/37269590-c4ebea5e-25d3-11e8-8e2e-2d97a07a750f.png)

----

* [ ] Avoid landing page redirects ([read more](https://developers.google.com/speed/docs/insights/AvoidRedirects))

prevent the following chain:
![image](https://user-images.githubusercontent.com/3581741/37269664-409332fc-25d4-11e8-8a8a-e48cd833b2f8.png)

----

* [ ] Leverage browser caching ([read more](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching))

for the following cacheable resources:
https://www.google-analytics.com/analytics.js (2 hours)
https://www.gizra.com/assets/javascript/script.js (4 hours)
https://www.gizra.com/assets/stylesheets/style.css (4 hours)
https://www.gizra.com/…bower_components/anchor-js/anchor.min.js (4 hours)
https://www.gizra.com/…74/cloudflare-static/email-decode.min.js (2 days)

----

**Comment by adamhstewart** [comment]
closed in favor of #725
