### ISSUE TITLE
SEO/Performance Team page: Optimize images [1h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#677]
![image](https://user-images.githubusercontent.com/3581741/37270816-f1b634fe-25d8-11e8-8ab0-dad817cf0852.png)

optimize team photos, consider using [ImageOptim](https://imageoptim.com/mac)
![image](https://user-images.githubusercontent.com/3581741/37270760-b0b6f6b4-25d8-11e8-9cb6-e384bfb9cff5.png)

**Comment by IshaDakota** [comment]
@noamoss I'd be happy if you wanted to optimize the images ;)

**Comment by noamoss** [comment]
@IshaDakota 

https://drive.google.com/open?id=1URoX0wq8rgI0oSSLVWGp28WZ_GErRbs5

Alex's photo is exceptionally big (3.7 mb). I added another version (~1mb, still bigger than all other). Would consider to  ask for a smaller file)

**Comment by IshaDakota** [comment]
@DavidHernandez images [here](https://drive.google.com/drive/folders/1URoX0wq8rgI0oSSLVWGp28WZ_GErRbs5)

**Comment by DavidHernandez** [comment]
@IshaDakota I guess this issue can be closed now?

**Comment by IshaDakota** [comment]
deployed
