### ISSUE TITLE
SEO/Performance: lazy loading of team members images [2h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#678]
![image](https://user-images.githubusercontent.com/3581741/37270880-320a2696-25d9-11e8-91de-17ee06e24911.png)

[read more](https://developers.google.com/web/tools/lighthouse/audits/offscreen-images)

**Comment by IshaDakota** [comment]
@noamoss This is a pretty ambitious task (would require many more than 2 hours) and I'm not sure that with the number of images on that page we gain any discernible benefit. More benefit would be gained from #677 . 

Unless someone is particularly interested in learning the technique, I'd close this one.

**Comment by noamoss** [comment]
sure. closing issue, and if I will find someone interested to learn it I will re-open.
