### ISSUE TITLE
SEO/Accessibility: Team page links don't have a discernable name [1h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/gizra.com#679]
Link text (and alternate text for images, when used as links) must be discernible by a screen reader, must not have a duplicate label, and must be focusable.

([read more](https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse))

list of failing links:
![image](https://user-images.githubusercontent.com/3581741/37271100-3764393c-25da-11e8-82cb-fd458df4b60d.png)

**Comment by IshaDakota** [comment]
@noamoss I need a little more info here.

What makes a proper accessible link in the case where the link is an icon. My short research suggests that an `aria-label` is a proper method, but I'm not sure.

In this case would we make it: `aria-label="Adam Stewart's Twitter"`

**Comment by noamoss** [comment]
@IshaDakota 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

> In this case would we make it: aria-label="Adam Stewart's Twitter"?

exactly.

**Comment by IshaDakota** [comment]
deployed

**Comment by noamoss** [comment]
looks great.
