### ISSUE TITLE
Add Project: UNICEF

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#683]
The description is in "Gizra Project List - Master Copy" document.

**Comment by IshaDakota** [comment]
[Project list](https://docs.google.com/document/d/1ZhL0hcMG05x5lwh-YI4pLQHZKjLVvyy33sFw2qv_pUQ/edit?usp=sharing)

**Comment by OritGeron** [comment]
@RachelBaram @IshaDakota We need to get the Client's consent to include their project in our showcase. Can you take care of that, please?
