### ISSUE TITLE
Add Project: Unio by Harness

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/gizra.com#684]
The description is in "Gizra Project List - Master Copy" document.

**Comment by IshaDakota** [comment]
@DavidHernandez can you create the project listing here from [this doc](https://docs.google.com/document/d/1ZhL0hcMG05x5lwh-YI4pLQHZKjLVvyy33sFw2qv_pUQ/edit?usp=sharing)

**Comment by IshaDakota** [comment]
deployed
