### ISSUE TITLE
Striked text

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#696]
Is this intended?

![stripped_down_to_the_essence__value-driven_development_is_harsh](https://user-images.githubusercontent.com/125707/39254895-e3fcb682-48b3-11e8-8409-bdf5e30f3a37.jpg)

**Comment by IshaDakota** [comment]
uh oh @RachelBaram , when we need to explain the joke...


(It's actually my favorite part)

**Comment by RachelBaram** [comment]
@amitaibu Did you fully read it? Yes, it is intended.
