### ISSUE TITLE
Multiple improvements for mobile experience

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/gizra.com#702]
I couldn't find this reported anywhere else so here is it. There are a lot of room for improvement when using the site from a mobile phone. I don't know why, but most of this issues are only visible using a physical phone and not the browser emulator.

## Words per line

![selection_153](https://user-images.githubusercontent.com/5313631/40425545-0ef14b70-5e6f-11e8-8ff4-2fa5754b6fbd.png)

This is a comparison between the current site in a random blog post and Firefox reading distraction free mode. As you can see, you can actually read in one line on average a few more words that helps to keep the idea of the post. Font sizes are not so different, the main difference is how white and padding spaces is used in both displays. 

## Bio and dates

![selection_154](https://user-images.githubusercontent.com/5313631/40425680-6aa43860-5e6f-11e8-83c6-daf0d9170c84.png)

There is a lot of white-space what could be used to display the date and the name of the author next to the photo, instead having to break the line.

## Comments

![selection_155](https://user-images.githubusercontent.com/5313631/40425772-b202537c-5e6f-11e8-8f23-8c995f48a79d.png)

There is a lot of non useful padding for comments.

## Our story

Same spacing issues applies for our story section. Also since paddings are different, the logo breaks the slogan into two lines.

![selection_156](https://user-images.githubusercontent.com/5313631/40426072-81699206-5e70-11e8-8f05-6c89b683a43e.png)

**Comment by amitaibu** [comment]
Good points! It gave me the push I needed to play around with tachyons 😄 

https://github.com/Gizra/gizra.com/pull/704
