### ISSUE TITLE
Clicked Header goes behind sticky navbar

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#731]
User clicks on anchor

![stripped_down_to_the_essence__value-driven_development_is_harsh](https://user-images.githubusercontent.com/125707/42809174-a3682b06-89bd-11e8-904c-8be36bd0e142.jpg)

Header is hidden behind navbar

![stripped_down_to_the_essence__value-driven_development_is_harsh](https://user-images.githubusercontent.com/125707/42809194-b60633ac-89bd-11e8-8570-eaab68ac781a.jpg)

**Comment by adamhstewart** [comment]
#733 deployed
